name: "Publish Docker Image to Docker Hub"

on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo ahmed
      - name: "before printing the folder containts"
        run: ls
      - uses: actions/checkout@v3
      - name: "after printing the folder containts"
        run: ls
      - uses: actions/checkout@v3
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}}  --password ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
      - name: " building docker "
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME}}/my-appp
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKER_USERNAME}}/my-appp
